package model

// Diff represents a single file change in a git diff.
type Diff struct {
	OldPath        string `json:"old_path"`
	NewPath        string `json:"new_path"`
	Diff           string `json:"diff"`
	NewFileContent string `json:"new_file_content"`
	IsBinary       bool   `json:"is_binary"`
	IsDeleted      bool   `json:"is_deleted"`
	IsNew          bool   `json:"is_new"`
	Insertions     int64  `json:"insertions"`
	Deletions      int64  `json:"deletions"`
}

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path            string `json:"path"`
	Content         string `json:"content"`
	SuggestionCode  string `json:"suggestion_code,omitempty"`
	StartLine       int    `json:"start_line"`
	EndLine         int    `json:"end_line"`
	Thinking        string `json:"thinking,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
